// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMDYy7l9gFrnA3CUwYZgXuDMnMVMpSX9g',
    appId: '1:170306745579:web:4f08a6b2438fbdbf15baae',
    messagingSenderId: '170306745579',
    projectId: 'catholic-terps-app',
    authDomain: 'catholic-terps-app.firebaseapp.com',
    storageBucket: 'catholic-terps-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhaTmToh16r1JCgSjIUggpHiVekqIRbI4',
    appId: '1:170306745579:android:e91d4beb847dbe9115baae',
    messagingSenderId: '170306745579',
    projectId: 'catholic-terps-app',
    storageBucket: 'catholic-terps-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOOXhWdBk0wUG3h1tj-5qrLE9_ptoiFQ',
    appId: '1:170306745579:ios:1803a3c67ae281bc15baae',
    messagingSenderId: '170306745579',
    projectId: 'catholic-terps-app',
    storageBucket: 'catholic-terps-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhOOXhWdBk0wUG3h1tj-5qrLE9_ptoiFQ',
    appId: '1:170306745579:ios:1803a3c67ae281bc15baae',
    messagingSenderId: '170306745579',
    projectId: 'catholic-terps-app',
    storageBucket: 'catholic-terps-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMDYy7l9gFrnA3CUwYZgXuDMnMVMpSX9g',
    appId: '1:170306745579:web:74e5411fdf5d125715baae',
    messagingSenderId: '170306745579',
    projectId: 'catholic-terps-app',
    authDomain: 'catholic-terps-app.firebaseapp.com',
    storageBucket: 'catholic-terps-app.appspot.com',
  );

}